// Each optional note asks the player to reason from a checkable historical clue.
// The fictional inn is never presented as a documented Tang-dynasty site.
window.SilkRoadHistoricalNotes = Object.freeze([
  Object.freeze({
    id: "well",
    kind: "驿站札记",
    title: "一口井，够一座城吗？",
    teaser: "同在吐鲁番，交河与高昌也用不同办法取水。",
    chapter: 2,
    repairId: "lv2_well",
    markerLabel: "井台札记",
    glyph: "井",
    clueLabel: "吐鲁番 · 唐代及沿线遗址",
    clueTitle: "交河有深井，高昌靠河渠",
    evidence: "交河城内留下了多口深井；唐代高昌城则有河渠引水的记载。ICOMOS 接受的勘误，还纠正了‘高昌靠坎儿井’的旧说。",
    question: "若要在流沙驿以外再设落脚点，掌柜该先做什么？",
    choices: ["照搬井台，沿路都修同样的井", "先看当地地形与水源，再定取水办法"],
    answerIndex: 1,
    feedback: "交河的深井与唐代高昌的河渠提醒我们：井可以供水，却不是每座城镇的通用答案。",
    takeaway: "水源决定落脚点如何生存；取水必须因地制宜。",
    reconstruction: "修井带来新旅人的玩法，参考了水利支撑聚落与行旅的历史关系。",
    fiction: "流沙驿、周甲和这口井均为游戏虚构，并非交河或高昌遗址的复原。",
    sources: [
      { label: "UNESCO / ICOMOS｜长安—天山廊道事实更正，第16页", url: "https://whc.unesco.org/document/130566" },
      { label: "UNESCO 世界遗产中心｜廊道旧综述（水利细节以勘误为准）", url: "https://whc.unesco.org/en/list/1442" },
    ],
  }),
  Object.freeze({
    id: "cargo",
    kind: "驿站札记",
    title: "一匹绢，是货也是钱",
    teaser: "货棚里清点的绢，可能也是下一笔交易的支付手段。",
    chapter: 4,
    repairId: "lv4_south_shed",
    markerLabel: "货棚札记",
    glyph: "绢",
    clueLabel: "西州市场 · 公元742年",
    clueTitle: "马价按绢匹计算",
    evidence: "大英博物馆展签引用公元742年西州市场的官定马价，以绢匹数计价。唐代素绢既是商品，也能用于发薪、纳税和交易。",
    question: "客商把一匹绢送进货棚，它在交易中算什么？",
    choices: ["只能是待售货物", "只能当作钱来付", "两者都可能"],
    answerIndex: 2,
    feedback: "唐代的绢可以被买卖，也可以充当支付手段；这不意味着所有交易都不用铜钱。",
    takeaway: "同一匹绢，在唐代可能兼有商品与支付手段两种角色。",
    reconstruction: "游戏借货棚清点货物的场景，让玩家辨认一件物品在交易中的不同用途。",
    fiction: "流沙驿的绢匹货签与这笔交易是游戏设定；公元742年的马价记录属于西州。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览完整展签：Silk as currency", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "sogdian",
    kind: "路上见闻",
    title: "一支舞，也走过丝路",
    teaser: "路上的人带来的，除了货物，还有能留在壁画里的舞步。",
    chapter: 1,
    orderId: "order_003_sogdian_humabing",
    glyph: "舞",
    clueLabel: "敦煌 · 唐代莫高窟第220窟",
    clueTitle: "壁画里有胡旋舞",
    evidence: "国际敦煌项目介绍，粟特人曾在敦煌等商镇形成社群，胡旋舞随人群往来传入。唐代莫高窟第220窟的壁画留有舞者形象。",
    question: "这幅壁画最直接支持哪种说法？",
    choices: ["唐代敦煌的艺术里出现过胡旋舞", "每位粟特商人都会跳胡旋舞"],
    answerIndex: 0,
    feedback: "壁画留下了胡旋舞题材，是文化交流的线索；它不能说明每位粟特商人的本领，更不是游戏人物的履历。",
    takeaway: "丝路交流不只有买卖；图像也能留下文化流动的证据。",
    reconstruction: "游戏用胡麻饼订单引出一位旅人，再借他打开商人参与文化交流的话题。",
    fiction: "这位胡商、他的订单和撒马尔罕炉火的回忆均为虚构；壁画不是他的履历。",
    sources: [
      { label: "大英图书馆·国际敦煌项目｜多元文化的敦煌", url: "https://idp.bl.uk/discover/learning/dunhuang/dunhuang-articles/the-cultural-melting-pot/multicultural-dunhuang/" },
      { label: "史密森学会｜唐代粟特舞者", url: "https://sogdians.si.edu/sogdian-dancer/" },
    ],
  }),
]);
