// Player-facing quizzes use factual surprises, not source-evaluation prompts.
// Fiction notes are internal editorial checks, never displayed in the quiz.
window.SilkRoadHistoricalNotes = Object.freeze([
  Object.freeze({
    id: "well",
    kind: "驿站札记",
    title: "同在吐鲁番，取水办法一样吗？",
    teaser: "修好井台，看看两座古城各自怎样找水。",
    chapter: 2,
    repairId: "lv2_well",
    markerLabel: "井台札记",
    glyph: "井",
    clueLabel: "吐鲁番 · 两座古城",
    clueTitle: "交河深井补水，高昌河渠引水",
    evidence: "交河城内留下了多口用于补水的深井；唐代高昌城则有河渠引水的记载。世界遗产文件还专门更正了‘高昌靠坎儿井’的旧说。",
    question: "猜猜看：交河与唐代高昌，分别怎样补水？",
    choices: ["两座城都靠河渠", "交河引河渠，高昌凿深井", "交河凿深井，高昌引河渠"],
    answerIndex: 2,
    feedback: "交河的答案是深井，高昌是河渠。两城相距不远，用水办法却不同；世界遗产文件还专门纠正过“高昌靠坎儿井”的旧说。",
    takeaway: "丝路沿线的用水办法，会随地形和水源而变。",
    fiction: "流沙驿、周甲和这口井均为游戏虚构，并非交河或高昌遗址的复原。",
    image: {
      src: "./assets/history/jiaohe-well.webp",
      alt: "交河故城的水井遗址，井口围着土坯，背景是古城残墙",
      caption: "交河故城水井（今景；照片经等比例缩放与格式转换，未裁剪）。",
      creditLabel: "摄影：HaziiDozen ↗",
      creditUrl: "https://commons.wikimedia.org/wiki/File:%E4%BA%A4%E6%B2%B3%E6%95%85%E5%9F%8E%E6%B0%B4%E4%BA%95%3B_a_water_well_in_Jiaohe_City.jpg",
      licenseLabel: "CC BY-SA 4.0 ↗",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
    sources: [
      { label: "UNESCO / ICOMOS｜长安—天山廊道事实更正，第16页", url: "https://whc.unesco.org/document/130566" },
      { label: "UNESCO 世界遗产中心｜廊道旧综述（水利细节以勘误为准）", url: "https://whc.unesco.org/en/list/1442" },
    ],
  }),
  Object.freeze({
    id: "cargo",
    kind: "驿站札记",
    title: "货棚里的一张马价单",
    teaser: "公元742年的西州市场，马价的单位有点出人意料。",
    chapter: 4,
    repairId: "lv4_south_shed",
    markerLabel: "货棚札记",
    glyph: "绢",
    clueLabel: "西州市场 · 公元742年",
    clueTitle: "马价按绢匹计算",
    evidence: "大英博物馆展签引用了公元742年西州市场的官定马价，以绢匹数记录不同马匹的价格。",
    question: "猜猜看：当时西州的官定马价，用什么来计算？",
    choices: ["铜钱的贯数", "绢的匹数", "粮食的石数"],
    answerIndex: 1,
    feedback: "是绢的匹数！唐代素绢不只能做衣料，也可用来发薪、纳税和交易；铜钱当然也没有消失。",
    takeaway: "一匹绢，既可能是货物，也可能用来付账。",
    fiction: "流沙驿的绢匹货签与这笔交易是游戏设定；公元742年的马价记录属于西州。",
    image: {
      src: "./assets/history/tang-silk-textile.webp",
      alt: "唐代八世纪紫地团花纹锦残片，织有浅色团花图案",
      caption: "唐代紫地团花纹锦（8世纪实物；并非西州马价文书）。",
      creditLabel: "大都会艺术博物馆藏 ↗",
      creditUrl: "https://www.metmuseum.org/art/collection/search/52098",
      licenseLabel: "开放馆藏 · CC0 ↗",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    },
    sources: [
      { label: "大英博物馆｜Silk Roads 展览完整展签：Silk as currency", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "sogdian",
    kind: "路上见闻",
    title: "路上的舞步有多快？",
    teaser: "路上的人带来的，还有让唐人看得眼花的表演。",
    chapter: 1,
    orderId: "order_003_sogdian_humabing",
    glyph: "舞",
    clueLabel: "敦煌 · 唐代莫高窟第220窟",
    clueTitle: "旋转的舞姿与胡旋舞",
    evidence: "敦煌研究院认为，莫高窟第220窟一组旋转的舞姿大概表现了传自中亚的胡旋舞；舞种辨认仍属图像解释。国际敦煌项目也记述粟特人在敦煌等商镇形成社群。",
    question: "猜猜看：第220窟的哪处动作，让研究者联想到胡旋舞？",
    choices: ["两人席地，面向彼此击鼓", "展臂挥巾，绺发似在旋转", "舞者列队，举弓作射猎状"],
    answerIndex: 1,
    feedback: "敦煌研究院描述那组舞者“展臂挥巾，绺发飘扬，似在旋转”，因而推测可能是胡旋舞。下图的唐代舞人壶来自另一件器物，壶上人物的身份尚不能确定。",
    takeaway: "丝路交流不只有买卖，歌舞也能走得很远。",
    fiction: "这位胡商、他的订单和撒马尔罕炉火的回忆均为虚构；壁画不是他的履历。",
    image: {
      src: "./assets/history/tang-dancer-pot.webp",
      alt: "唐代长沙窑壶的壶身贴饰着一位舞者，舞者举起双手",
      caption: "唐代长沙窑舞人纹壶（约9世纪；并非莫高窟壁画）。",
      creditLabel: "大都会艺术博物馆藏 ↗",
      creditUrl: "https://www.metmuseum.org/art/collection/search/42395",
      licenseLabel: "开放馆藏 · CC0 ↗",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    },
    sources: [
      { label: "敦煌研究院｜莫高窟第220窟乐舞图", url: "https://www.dha.ac.cn/info/1425/3598.htm" },
      { label: "大英图书馆·国际敦煌项目｜多元文化的敦煌", url: "https://idp.bl.uk/discover/learning/dunhuang/dunhuang-articles/the-cultural-melting-pot/multicultural-dunhuang/" },
      { label: "史密森学会｜唐代粟特舞者", url: "https://sogdians.si.edu/sogdian-dancer/" },
    ],
  }),
  Object.freeze({
    id: "dried_cheese",
    kind: "驿站札记",
    title: "一团干酪，路上怎么吃？",
    teaser: "修好炉灶，翻到一则能带乳食远行的古法。",
    chapter: 1,
    repairId: "kitchen_repair",
    markerLabel: "乳食札记",
    glyph: "酪",
    clueLabel: "《齐民要术》 · 远行乳食",
    clueTitle: "干酪可作远行储粮",
    evidence: "北魏《齐民要术》的《作干酪法》记下制成干酪后可以长期保存，并明确说它可“供远行”。这是一条较晚唐更早的做法记载。",
    question: "猜猜看：古书说旅人带着干酪，还能怎样吃？",
    choices: ["泡进凉水里生饮", "夹进果干里晾晒", "削进粥浆里煮"],
    answerIndex: 2,
    feedback: "削一片进热粥或浆，乳味就回来了。《齐民要术》还说干酪可久存、可供远行；但没有证据说流沙驿的人照此制作。",
    takeaway: "食物能否保存，决定了它能不能走得更远。",
    fiction: "流沙驿的乳食订单、炉灶与旅人携带干酪的情节均为虚构；北魏做法不能直接当成晚唐沙州惯例。",
    sources: [
      { label: "《齐民要术》卷六｜作干酪法原文", url: "https://zh.wikisource.org/zh-hans/%E9%BD%8A%E6%B0%91%E8%A6%81%E8%A1%93/%E5%8D%B7%E7%AC%AC%E5%85%AD" },
    ],
  }),
  Object.freeze({
    id: "oasis_routes",
    kind: "驿站札记",
    title: "过了敦煌，路只有一条吗？",
    teaser: "西市开张，看看商旅怎样绕开大漠。",
    chapter: 2,
    repairId: "lv2_west_market",
    markerLabel: "商路札记",
    glyph: "路",
    clueLabel: "敦煌 · 塔里木盆地",
    clueTitle: "商路可沿沙漠南北两侧行进",
    evidence: "大英博物馆的丝路展说明：从敦煌附近出发，驼队可以选择塔里木盆地的北线或南线，绕行塔克拉玛干与罗布沙漠，再经过绿洲城镇补给。",
    question: "猜猜看：驼队从敦煌往西，怎样绕过两片大漠？",
    choices: ["在沙漠中央走一条直线", "沿南北两侧接续绿洲", "沿一条大河一直乘船"],
    answerIndex: 1,
    feedback: "是沿南北两侧的绿洲路线。途中还需要能停下饮水、休息和补给的城镇。",
    takeaway: "丝路是一张依赖绿洲的路网，不是一条笔直大道。",
    fiction: "流沙驿西市及商队路线是叙事组合；这条史料只说明区域路网，不能定位游戏驿站。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览：沙漠路线与绿洲城镇", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "sanskrit_sutra",
    kind: "驿站札记",
    title: "看不懂梵文，也能跟着读？",
    teaser: "楼馆迎来求法僧人，一页敦煌写本藏着读音线索。",
    chapter: 3,
    repairId: "lv3_upper_hall",
    markerLabel: "写本札记",
    glyph: "经",
    clueLabel: "敦煌藏经洞 · 十世纪",
    clueTitle: "梵文《心经》旁有汉字注音",
    evidence: "大英博物馆展出一件出自莫高窟第17窟的折叠式《心经》写本：梵文经文旁列有汉字音译，阅读方向也迁就汉字的竖排方式。馆方将它断代为十世纪。",
    question: "猜猜看：敦煌一件梵文《心经》写本，怎样提示读音？",
    choices: ["旁列汉语意译", "旁列藏文注音", "旁列汉字音译"],
    answerIndex: 2,
    feedback: "旁边排着汉字音译，提示的是读音，不是把经义逐句译成汉语。写本留下了跨语言学习经文的线索。",
    takeaway: "往来的人带来的，还有不同语言的知识。",
    fiction: "流沙驿的求法僧人与楼馆是虚构；该写本年代为十世纪，不能直接充当晚唐驿站的实物。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览：Reading Sanskrit in Chinese", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "guard_shoe",
    kind: "驿站札记",
    title: "一只旧鞋能说什么？",
    teaser: "东院留客后，看看边塞出土的小物件。",
    chapter: 3,
    repairId: "lv3_east_court",
    markerLabel: "行旅札记",
    glyph: "履",
    clueLabel: "麻扎塔格 · 边塞遗物",
    clueTitle: "毛毡鞋的鞋底与鞋跟补了皮",
    evidence: "大英博物馆展出一只麻扎塔格戍堡遗址发现的鞋，年代约为八世纪末至九世纪。它以厚毛毡制成，鞋底与鞋跟缝有皮革补片。",
    question: "猜猜看：边塞出土的毛毡鞋，哪些部位最需要补皮革？",
    choices: ["鞋面和鞋舌", "鞋底和鞋跟", "鞋口和绑带"],
    answerIndex: 1,
    feedback: "是鞋底和鞋跟。小小的补片提醒我们：漫长道路也留在穿用之物上。",
    takeaway: "日常旧物，也能保存行旅生活的证据。",
    fiction: "游戏东院旅人的鞋履是视觉与叙事设计；馆藏实物出自麻扎塔格，不属于流沙驿。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览：Everyday life at a guard-station", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "sogdian_vessel",
    kind: "驿站札记",
    title: "货棚里的器形会走路？",
    teaser: "东棚聚货，看看工匠怎样借鉴远方器物。",
    chapter: 4,
    repairId: "lv4_east_shed",
    markerLabel: "器物札记",
    glyph: "器",
    clueLabel: "粟特与唐代 · 器物交流",
    clueTitle: "陶壶也会模仿金属器的样子",
    evidence: "大英博物馆丝路展介绍，撒马尔罕地区的一件陶壶在外形与金属光泽上模仿粟特金属器；这一类金属器传播到唐代中国，启发了当地工匠。",
    question: "猜猜看：粟特工匠制作陶壶时，借了哪种器物的外形与光泽？",
    choices: ["金属器", "玻璃器", "漆木器"],
    answerIndex: 0,
    feedback: "是金属器。陶土没有变成金属，但工匠借来了金属器的形与光泽；器物传播时，样式也会跟着走。",
    takeaway: "贸易让物品流动，也让工艺和样式流动。",
    fiction: "流沙驿东棚、货物与器皿摆放均为虚构；馆藏陶壶不是驿站出土物。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览：Manufacture and movement of luxury goods", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "first_seat",
    kind: "驿站札记",
    title: "路边宿处，只招待人吗？",
    teaser: "前厅有了座位，再想想商旅还带来了什么。",
    chapter: 1,
    repairId: "tutorial_complete",
    markerLabel: "客座札记",
    glyph: "客",
    clueLabel: "丝路宿处 · 人与行装",
    clueTitle: "商队的牲口和货物也要安顿",
    evidence: "联合国教科文组织介绍，丝路沿线的商队宿处需要让旅人、载货牲口与货物一同停驻，并提供遮蔽、食物与饮水。所举安纳托利亚驿馆是更晚、更西的比较案例。",
    question: "猜猜看：一队商旅投宿，除了人，宿处还得接住什么？",
    choices: ["只需额外安顿车夫", "只需额外看管账本", "载货牲口和货物"],
    answerIndex: 2,
    feedback: "牲口要歇脚，货物要有处存放。沿路的宿处承担的不只是“给人一张床”，也让商队能继续走。",
    takeaway: "一处能停靠的地方，连接着吃住、运输和交易。",
    fiction: "流沙驿前厅和人物均为虚构。材料中的驿馆跨地区、跨时期，不是晚唐沙州宿处的平面图。",
    sources: [
      { label: "UNESCO 世界遗产中心｜塞尔柱商队驿馆说明", url: "https://whc.unesco.org/en/tentativelists/1403" },
    ],
  }),
  Object.freeze({
    id: "library_cave",
    kind: "驿站札记",
    title: "藏经洞里，只有经卷吗？",
    teaser: "食单上墙时，看看一间小洞怎样留住不同材料。",
    chapter: 1,
    repairId: "codex_first_phase",
    markerLabel: "食单札记",
    glyph: "卷",
    clueLabel: "敦煌 · 莫高窟第17窟",
    clueTitle: "写本之外，还有绘画与织物",
    evidence: "大英博物馆介绍，莫高窟第17窟藏经洞封存的除了大量写本和文书，还包括绘画、纺织品和版画。不同材料共同保存了敦煌的生活与信仰线索。",
    question: "猜猜看：藏经洞里除了写本，还发现过哪一组东西？",
    choices: ["陶瓷、铜镜和钱币", "绘画、织物和版画", "木简、石碑和铠甲"],
    answerIndex: 1,
    feedback: "还有绘画、织物和版画。历史不只留在字里，也留在图像和手工制作的物件上。",
    takeaway: "保存材料的种类越多，越能从不同侧面接近过去。",
    fiction: "流沙驿食单和佛寺女施主为虚构；藏经洞的藏品不属于游戏驿站。",
    sources: [
      { label: "大英博物馆｜Exploring the Silk Roads：藏经洞藏品", url: "https://www.britishmuseum.org/collection/china/exploring-silk-roads" },
    ],
  }),
  Object.freeze({
    id: "marrow_cake",
    kind: "驿站札记",
    title: "古书里的饼，甜味从哪来？",
    teaser: "前厅开席，翻开一则写得很细的古法饼食。",
    chapter: 2,
    repairId: "lv2_front_feast",
    markerLabel: "开席札记",
    glyph: "饼",
    clueLabel: "《齐民要术》 · 髓饼法",
    clueTitle: "髓脂与蜜一同和进面里",
    evidence: "北魏《齐民要术》卷九《髓饼法》写到用髓脂和蜜和面，再放进胡饼炉烤熟。它是跨时期的饼食做法记录，并非流沙驿的菜单。",
    question: "猜猜看：古书里的髓饼，面里还和进了哪两样？",
    choices: ["髓脂与蜜", "葡萄与酒", "干酪与石榴汁"],
    answerIndex: 0,
    feedback: "是髓脂与蜜。古书连烤炉和不翻面的做法也记了下来，一张饼留下了不少厨房动作。",
    takeaway: "一条食谱能告诉我们的，往往不只是食物名称。",
    fiction: "流沙驿开席与髓饼上桌是叙事安排；北魏食谱不能直接代表晚唐沙州日常。",
    sources: [
      { label: "《齐民要术》卷九｜髓饼法原文", url: "https://zh.wikisource.org/wiki/%E9%BD%8A%E6%B0%91%E8%A6%81%E8%A1%93/%E5%8D%B7%E7%AC%AC%E4%B9%9D" },
    ],
  }),
  Object.freeze({
    id: "day_journey",
    kind: "驿站札记",
    title: "下一处歇脚地，要走多久？",
    teaser: "花架能避雨，远途商旅也要盘算下一晚住哪。",
    chapter: 2,
    repairId: "lv2_flower_rack",
    markerLabel: "歇脚札记",
    glyph: "宿",
    clueLabel: "丝路 · 商旅宿处",
    clueTitle: "宿处常按一日行程布设",
    evidence: "联合国教科文组织的丝路概述指出，商队宿处通常相隔约一天的路程，使商人及货物尽量不在野外过夜。这是对广阔路网的概述，不是沙州里程表。",
    question: "猜猜看：丝路上的商旅宿处，常隔多长一段路？",
    choices: ["约三日行程", "约半日行程", "约一日行程"],
    answerIndex: 2,
    feedback: "大致是一日行程。选址还要看水源、地形与安全；赶得上下一处宿地，夜里才更有保障。",
    takeaway: "道路能走多远，也取决于沿途能否停下。",
    fiction: "流沙驿花架与当地旅人故事均为虚构；概述中的间距不能套算到游戏地图。",
    sources: [
      { label: "UNESCO｜About the Silk Roads：商旅宿处", url: "https://www.unesco.org/en/silk-roads/about-silk-roads" },
    ],
  }),
  Object.freeze({
    id: "pedlar_figurine",
    kind: "驿站札记",
    title: "弯着腰的陶俑，背着什么故事？",
    teaser: "北铺开张，认一认唐代陶俑里的小生意人。",
    chapter: 2,
    repairId: "lv2_north_shop",
    markerLabel: "铺面札记",
    glyph: "贩",
    clueLabel: "唐代 · 背货陶俑",
    clueTitle: "弯腰负货的行商形象",
    evidence: "大英博物馆展示一件唐代陶俑，人物弯腰背负待售货品；馆方将其解释为小贩形象。陶俑表现的是一种人物类型，不是某位流沙驿商人的肖像。",
    question: "猜猜看：唐代有尊弯腰背货的陶俑，馆方认为他在做什么？",
    choices: ["主持佛寺法会", "带货叫卖", "守边放烽"],
    answerIndex: 1,
    feedback: "是一位带货的小贩。丝路上做买卖的人，不只有远行的大商队。",
    takeaway: "小贩、店客与工匠，也组成了往来路上的日常。",
    fiction: "北铺摊主与交易为虚构；陶俑的具体身份和经历无法从造型直接确定。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览：Foreign populations", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "sea_water",
    kind: "驿站札记",
    title: "海上丝路，船最怕缺什么？",
    teaser: "南铺接起水路，想想远海航行的补给。",
    chapter: 2,
    repairId: "lv2_south_shop",
    markerLabel: "水路札记",
    glyph: "舟",
    clueLabel: "丝路海路 · 港口补给",
    clueTitle: "远洋商船要补充饮用淡水",
    evidence: "联合国教科文组织介绍，丝路的海上航线也依靠沿岸港口；船只在那里贸易、上岸并补给淡水。缺少可饮用的水，是远海航行的重要风险。",
    question: "猜猜看：远海商船靠港，除了货物，最要紧补上什么？",
    choices: ["新鲜蔬果", "修船木料", "饮用淡水"],
    answerIndex: 2,
    feedback: "是淡水。海水包围着船，却不能直接解渴；港口的补给能力决定船能否继续航行。",
    takeaway: "丝路既有陆路，也有依赖港口的海路。",
    fiction: "流沙驿南铺和所谓“水路”是游戏叙事；本题说的是海上丝路，不能把敦煌写成海港。",
    sources: [
      { label: "UNESCO｜About the Silk Roads：海上航线与港口", url: "https://www.unesco.org/en/silk-roads/about-silk-roads" },
    ],
  }),
  Object.freeze({
    id: "travelling_monk",
    kind: "驿站札记",
    title: "行脚僧身边，竟跟着谁？",
    teaser: "北院留客，看看敦煌画里想象的远行。",
    chapter: 3,
    repairId: "lv3_north_court",
    markerLabel: "僧行札记",
    glyph: "僧",
    clueLabel: "敦煌藏经洞 · 神异僧人画",
    clueTitle: "画中的行脚僧有虎相伴",
    evidence: "大英博物馆展出一幅敦煌藏经洞出土的行脚僧画，断代约公元851至900年。画中僧人乘云、身边伴有虎，并有佛像；这些元素强调他的神异身份。",
    question: "猜猜看：敦煌有幅神异僧人画，僧人身边竟跟着哪种动物？",
    choices: ["虎", "骆驼", "孔雀"],
    answerIndex: 0,
    feedback: "是一只虎。不过这幅画呈现的是神异人物，不应当作普通僧人带虎赶路的日常记录。",
    takeaway: "图像也有自己的叙事方式，读画要看它想表达什么。",
    fiction: "流沙驿的求法僧人及北院均为虚构；藏经洞图像不是他的肖像。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览：A supernatural travelling monk", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "beacon_signals",
    kind: "驿站札记",
    title: "夜里的烽燧，靠什么说话？",
    teaser: "西门通路，听一听古代边塞怎样传警。",
    chapter: 3,
    repairId: "lv3_west_gate",
    markerLabel: "烽燧札记",
    glyph: "烽",
    clueLabel: "唐代边塞 · 烽燧值守",
    clueTitle: "白天候烟，夜里观火",
    evidence: "有关唐代烽燧的考古介绍引用“昼堠烟，夜观火”，指出烽子按昼夜轮值，以烟、火等信号传递边防信息。不同军情还对应不同数量的火。",
    question: "猜猜看：唐代烽子夜里传警，远处最容易看见什么？",
    choices: ["彩旗", "火光", "铜镜反光"],
    answerIndex: 1,
    feedback: "是火光。白日候烟、夜里观火，烽燧让分散的边塞哨所能更快互通消息。",
    takeaway: "一段道路要安全，还需要背后有人长期守望。",
    fiction: "流沙驿西门与值守人物是虚构；引用的是唐代边防制度，不等于游戏建筑的直接原型。",
    sources: [
      { label: "考古进行时｜唐代戍边烽燧生活", url: "https://www.tongren.gov.cn/2022/0115/259102.shtml" },
    ],
  }),
  Object.freeze({
    id: "clamp_dye",
    kind: "驿站札记",
    title: "布上的团花，是画上去的吗？",
    teaser: "花影庭园里，看看敦煌织物怎样留下花纹。",
    chapter: 3,
    repairId: "lv3_garden",
    markerLabel: "花纹札记",
    glyph: "花",
    clueLabel: "敦煌藏经洞 · 唐代织物",
    clueTitle: "木夹板帮助挡染成花",
    evidence: "大英博物馆展示出自敦煌藏经洞的八至九世纪丝织残片：制作者用木夹遮住布面的一部分，再浸入染液，形成团花与飞雁等图案。馆方还用染料分析辅助复原原来的色彩。",
    question: "猜猜看：织物上的团花，工匠用什么挡住染料？",
    choices: ["陶碗", "竹简", "木夹板"],
    answerIndex: 2,
    feedback: "是木夹板。被夹住的地方不容易上色，松开后花纹就显出来了；图案并非全靠画笔描上去。",
    takeaway: "一块旧织物，也能留下工匠的制作方法。",
    fiction: "流沙驿庭园、人物织物与花纹摆设均为虚构；馆藏残片不是此地遗物。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览：Rich colours and patterns", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "beacon_workers",
    kind: "驿站札记",
    title: "守望楼上的人，只负责点火吗？",
    teaser: "望楼通途，看看唐代烽子的日常工作。",
    chapter: 3,
    repairId: "lv3_watchtower",
    markerLabel: "望楼札记",
    glyph: "守",
    clueLabel: "唐代边塞 · 烽子职责",
    clueTitle: "候望之外，还要传文书、备粮草",
    evidence: "唐代边塞考古资料中的烽子，除了候望放烽，还要处理文书、传递符牒、准备烽具和粮草，也可能参与耕作。守望是一套日常劳动。",
    question: "猜猜看：唐代烽子不放烽的时候，还要忙什么？",
    choices: ["传递文书、准备粮草", "只在楼上等待换班", "只替商人鉴定丝绢"],
    answerIndex: 0,
    feedback: "还得传文书、备粮草，有人甚至要耕作。烽燧能运转，靠的是一连串不起眼的工作。",
    takeaway: "道路背后的劳动，常比一座望楼更难看见。",
    fiction: "游戏望楼及人物是虚构；唐代烽子职责只用作边塞生活参照。",
    sources: [
      { label: "考古进行时｜唐代戍边烽燧生活", url: "https://www.tongren.gov.cn/2022/0115/259102.shtml" },
    ],
  }),
  Object.freeze({
    id: "wine_vessels",
    kind: "驿站札记",
    title: "葡萄酒来了，酒杯也变了？",
    teaser: "中市开席，看看饮品怎样带来新的器形。",
    chapter: 4,
    repairId: "lv4_central_market",
    markerLabel: "酒器札记",
    glyph: "盏",
    clueLabel: "唐代 · 葡萄酒与饮器",
    clueTitle: "有酒杯模仿伊朗地区的角状饮器",
    evidence: "大英博物馆介绍，唐代葡萄酒的流行与新式饮器有关。一件陶杯模仿伊朗地区角状饮器的形制，杯上还可见中亚人物与联珠纹。",
    question: "猜猜看：唐代一件新式饮酒杯，借鉴了哪种形状？",
    choices: ["中原的青铜鼎", "伊朗地区的角状饮器", "厨房里的蒸笼"],
    answerIndex: 1,
    feedback: "是角状饮器。饮品进入新的餐桌时，盛它的杯子也可能借来远方的外形。",
    takeaway: "饮食传播会连带改变餐桌上的器物。",
    fiction: "流沙驿中市的酒席与杯具是虚构；展出的唐代陶杯不是此地出土物。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览：Vessel shapes from the west", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "gift_list",
    kind: "驿站札记",
    title: "一件象牙，换回多少绢？",
    teaser: "南市连街，一张敦煌礼单写着物品往来。",
    chapter: 4,
    repairId: "lv4_south_street",
    markerLabel: "礼单札记",
    glyph: "礼",
    clueLabel: "敦煌写本 · 约公元894—907年",
    clueTitle: "一件象牙对应唐廷回赠二十匹绢",
    evidence: "大英博物馆介绍一份敦煌藏经洞出土的礼单：甘州回鹘向唐廷送礼，唐廷按物回赠不同绢帛；一件象牙对应二十匹绢。它记录的是外交馈赠，不是街市零售价格。",
    question: "猜猜看：敦煌一份外交礼单中，一件象牙对应回赠多少匹绢？",
    choices: ["两匹", "两百匹", "二十匹"],
    answerIndex: 2,
    feedback: "是二十匹绢。礼单把物品与回赠一一写下，让今天的人看到一次具体的往来。",
    takeaway: "一张清单，也能记录人群之间的关系。",
    fiction: "流沙驿南市交易为虚构；外交礼单不是游戏市场的物价表。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览：Diplomatic gifts", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "imitation_coin",
    kind: "驿站札记",
    title: "墓里的一枚金币，未必是真币？",
    teaser: "巷路相接，看看高昌附近出土的远方钱币形象。",
    chapter: 4,
    repairId: "lv4_lanes",
    markerLabel: "钱币札记",
    glyph: "钱",
    clueLabel: "吐鲁番阿斯塔那 · 墓葬遗物",
    clueTitle: "一枚仿拜占庭金币被放入口中",
    evidence: "大英博物馆丝路展介绍，高昌附近阿斯塔那的一座墓中，死者口中放着一枚仿拜占庭金币。附近墓葬还见有仿萨珊银币和中国铜钱。仿币说明图像与习俗的传播，不等于死者到过拜占庭。",
    question: "猜猜看：吐鲁番墓葬中一枚仿金币，模仿了哪里的币？",
    choices: ["拜占庭", "唐代长安", "古埃及"],
    answerIndex: 0,
    feedback: "模仿的是拜占庭金币。它出土在吐鲁番附近，却不能据此说墓主人去过遥远的拜占庭。",
    takeaway: "钱币的图样也会远行，使用方式还可能改变。",
    fiction: "流沙驿巷路与铜币系统是游戏设计；墓葬仿币不能视作流沙驿通用钱币。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览：Foreign coins and their adaptation", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "glass_bowl",
    kind: "驿站札记",
    title: "壁画里的一只钵，像什么材料？",
    teaser: "东院焕新，留意敦煌画家笔下的器物光泽。",
    chapter: 4,
    repairId: "lv4_east_court",
    markerLabel: "画中札记",
    glyph: "钵",
    clueLabel: "敦煌藏经洞 · 约公元851—900年",
    clueTitle: "绿莹莹的钵让人想到玻璃器",
    evidence: "大英博物馆一幅敦煌菩萨画中，菩萨手持的钵呈半透明绿色，并画出点状表面；馆方指出这些特征让人联想到萨珊地区的玻璃器。画中之钵不是一件出土玻璃实物。",
    question: "猜猜看：敦煌菩萨画中有只半透明的绿钵，借鉴了哪种远来器皿？",
    choices: ["竹编篮", "玻璃器", "皮革水囊"],
    answerIndex: 1,
    feedback: "是玻璃器的透亮感。远方器物即使没有摆在眼前，也可能进入画家的图像语言。",
    takeaway: "图像能记录人们怎样想象和使用异地物品。",
    fiction: "流沙驿东院和器皿陈设为虚构；壁画里的钵不能当作驿站实物。",
    sources: [
      { label: "大英博物馆｜Silk Roads 展览：Sasanian elements in Dunhuang", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "lantern_night",
    kind: "驿站札记",
    title: "晚唐敦煌的上元夜，只有灯吗？",
    teaser: "最后一段巷路亮起，读一读敦煌文书里的夜色。",
    chapter: 4,
    repairId: "lv4_lantern_city",
    markerLabel: "灯夜札记",
    glyph: "灯",
    clueLabel: "敦煌文书 · 上元夜",
    clueTitle: "灯笼火树旁，还有舞席歌筵",
    evidence: "敦煌研究院介绍，文书 S.2832 与 P.2631 提到上元夜街巷燃灯，以及舞席歌筵。这些文字提供了晚唐敦煌节夜的线索，但不是流沙驿某一晚的记录。",
    question: "猜猜看：敦煌文书写上元夜，灯火之外还有什么？",
    choices: ["烽火军令", "水车竞赛", "舞席歌筵"],
    answerIndex: 2,
    feedback: "还有舞席歌筵。灯照亮的不只一条路，也照见当时人聚在一起的节日时刻。",
    takeaway: "历史里的夜晚，也有人声与相聚。",
    fiction: "流沙驿终章灯市是设计叙事，不是对某一年敦煌上元节的复刻。",
    sources: [
      { label: "敦煌研究院｜上元节与敦煌燃灯文书", url: "https://www.dha.ac.cn/info/1157/2650.htm" },
    ],
  }),
]);
