// Player-facing quizzes use factual surprises, not source-evaluation prompts.
// Fiction notes are internal editorial checks, never displayed in the quiz.
window.SilkRoadHistoricalNotes = Object.freeze([
  Object.freeze({
    id: "well",
    kind: "驿站札记",
    title: "沙漠古城怎样找水？",
    teaser: "修好井台，猜猜吐鲁番古城的取水秘密。",
    chapter: 2,
    repairId: "lv2_well",
    markerLabel: "井台札记",
    glyph: "井",
    clueLabel: "吐鲁番 · 两座古城",
    clueTitle: "交河深井补水，高昌河渠引水",
    evidence: "交河城内留下了多口用于补水的深井；唐代高昌城则有河渠引水的记载。世界遗产文件还专门更正了‘高昌靠坎儿井’的旧说。",
    question: "猜猜看：交河城和唐代高昌城，取水办法完全一样吗？",
    choices: ["是，办法一样", "否，各有办法"],
    answerIndex: 1,
    feedback: "不一样！交河城内可见深井，唐代高昌城有河渠引水的记录；同在吐鲁番，供水设施也不尽相同。",
    takeaway: "丝路沿线的用水办法，会随地形和水源而变。",
    fiction: "流沙驿、周甲和这口井均为游戏虚构，并非交河或高昌遗址的复原。",
    image: {
      src: "./assets/history/jiaohe-well.webp",
      alt: "交河故城的水井遗址，井口围着土坯，背景是古城残墙",
      caption: "交河故城水井（今景；照片经等比例缩放与格式转换，未裁剪）。",
      creditLabel: "摄影：HaziiDozen ↗",
      creditUrl: "https://commons.wikimedia.org/wiki/File:%E4%BA%A4%E6%B2%B3%E6%95%85%E5%9F%8E%E6%B0%B4%E4%BA%95%3B_a_water_well_in_Jiaohe_City.jpg",
      licenseLabel: "CC BY-SA 4.0 ↗",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
    sources: [
      { label: "UNESCO / ICOMOS｜长安—天山廊道事实更正，第16页", url: "https://whc.unesco.org/document/130566" },
      { label: "UNESCO 世界遗产中心｜廊道旧综述（水利细节以勘误为准）", url: "https://whc.unesco.org/en/list/1442" },
    ],
  }),
  Object.freeze({
    id: "cargo",
    kind: "驿站札记",
    title: "货棚里的一张马价单",
    teaser: "公元742年的西州市场，马价的单位有点出人意料。",
    chapter: 4,
    repairId: "lv4_south_shed",
    markerLabel: "货棚札记",
    glyph: "绢",
    clueLabel: "西州市场 · 公元742年",
    clueTitle: "马价按绢匹计算",
    evidence: "大英博物馆展签引用了公元742年西州市场的官定马价，以绢匹数记录不同马匹的价格。",
    question: "猜猜看：当时西州的官定马价，用什么来计算？",
    choices: ["铜钱的贯数", "绢的匹数", "粮食的石数"],
    answerIndex: 1,
    feedback: "是绢的匹数！唐代素绢不只能做衣料，也可用来发薪、纳税和交易；铜钱当然也没有消失。",
    takeaway: "一匹绢，既可能是货物，也可能用来付账。",
    fiction: "流沙驿的绢匹货签与这笔交易是游戏设定；公元742年的马价记录属于西州。",
    image: {
      src: "./assets/history/tang-silk-textile.webp",
      alt: "唐代八世纪紫地团花纹锦残片，织有浅色团花图案",
      caption: "唐代紫地团花纹锦（8世纪实物；并非西州马价文书）。",
      creditLabel: "大都会艺术博物馆藏 ↗",
      creditUrl: "https://www.metmuseum.org/art/collection/search/52098",
      licenseLabel: "开放馆藏 · CC0 ↗",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    },
    sources: [
      { label: "大英博物馆｜Silk Roads 展览完整展签：Silk as currency", url: "https://www.britishmuseum.org/exhibitions/silk-roads/large-print-guide" },
    ],
  }),
  Object.freeze({
    id: "sogdian",
    kind: "路上见闻",
    title: "路上的舞步有多快？",
    teaser: "路上的人带来的，还有让唐人看得眼花的表演。",
    chapter: 1,
    orderId: "order_003_sogdian_humabing",
    glyph: "舞",
    clueLabel: "敦煌 · 唐代莫高窟第220窟",
    clueTitle: "旋转的胡旋舞",
    evidence: "唐代莫高窟第220窟的壁画留有胡旋舞题材。国际敦煌项目介绍，粟特人曾在敦煌等商镇形成社群，歌舞也随着人群往来传播。",
    question: "猜猜看：唐人喜欢的胡旋舞，最招牌的动作是什么？",
    choices: ["飞快旋转", "高高抛球", "双人击鼓"],
    answerIndex: 0,
    feedback: "是飞快旋转！下图的唐代舞人壶，也让我们看见舞者形象如何出现在日常器物上。壶上人物的身份还不能确定。",
    takeaway: "丝路交流不只有买卖，歌舞也能走得很远。",
    fiction: "这位胡商、他的订单和撒马尔罕炉火的回忆均为虚构；壁画不是他的履历。",
    image: {
      src: "./assets/history/tang-dancer-pot.webp",
      alt: "唐代长沙窑壶的壶身贴饰着一位舞者，舞者举起双手",
      caption: "唐代长沙窑舞人纹壶（约9世纪；并非莫高窟壁画）。",
      creditLabel: "大都会艺术博物馆藏 ↗",
      creditUrl: "https://www.metmuseum.org/art/collection/search/42395",
      licenseLabel: "开放馆藏 · CC0 ↗",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    },
    sources: [
      { label: "大英图书馆·国际敦煌项目｜多元文化的敦煌", url: "https://idp.bl.uk/discover/learning/dunhuang/dunhuang-articles/the-cultural-melting-pot/multicultural-dunhuang/" },
      { label: "史密森学会｜唐代粟特舞者", url: "https://sogdians.si.edu/sogdian-dancer/" },
    ],
  }),
]);
